# Create a dockerfile with node image
# start by pulling the python image
FROM python:3.8-alpine

# copy the requirements file into the image
COPY ./requirements.txt /app/requirements.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements.txt

# copy every content from the local file to the image
COPY . /app

# configure the container to run in an executed manner
ENTRYPOINT [ "python" ]

CMD ["view.py" ]

# Create a directory to hold the application code inside the image, this will be the working directory for your application


# Set the working directory to /usr/src/app

# Copy package.json and package-lock.json to the working directory

# Install npm 

# Copy the current directory contents into the container at /usr/src/app

# Make port 3000 available to the world outside this container

# Run Nodeserver.js when the container launches

# Write a docker comand to build the image and tag it as mynodeapp
